version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/src:cached
      - node_modules:/src/node_modules
      # ↑ 次回起動後にコメントアウトを解除
    working_dir: "/src"
    ports:
      - "3000:3000"
    tty: true
    environment:
    - HOST=0.0.0.0
    - port=3000
    - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
  db:
    image: postgres:13
    container_name: todoapp_postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  pgadmin:
    image: dpage/pgadmin4
    container_name: todoapp_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  db-data:
  node_modules:
